import { useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const user = useUser();
  const { data } = api.household.getAll.useQuery();

  console.log(data);

  return (
    <>
      <Head>
        <title>Recipe Book</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22>
              <text y=%22.9em%22 font-size=%2290%22>
                🥘
              </text>
            </svg>"
        ></link>
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#c9e2f0] to-[#f5f5f5]">
        <div>
          <h1 className="text-5xl font-bold text-gray-900">Recipe Book</h1>

          <h3>Households</h3>

          {data?.map((household) => (
            <div key={household.id}>
              <h4>{household.name}</h4>
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
